- name: "Add users with primary group sudo"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment }}"
    create_home: true
    group: sudo
    password: "{{ item.password }}"
    shell: "/bin/bash"
    state: "{{ item.state }}"
  with_items: "{{ users }}"
- name: "add authorized_key without validation of the certificate"
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "https://github.com/{{ item.name }}.keys"
    validate_certs: false
  with_items: "{{ users }}"
- name: "Install utilities"
  package :
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ packages }}"