name: Production Provisioning
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Ansible Log Level'
        required: false
        default: 'warning'
    tags:
      description: manual provisioning
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - name: Provision Production
      run: ansible-playbook provision.yml --inventory-file env/production --extra-vars="ansible_user=${{ secrets.ansible_user}} ansible_password=${{ secrets.ansible_password}}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_SSH_COMMON_ARGS: '-o PreferredAuthentications=password'
