name: Production Provisioning
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Manual Provisioning'
jobs:
  ansible:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}"
    - uses: actions/checkout@master
      with:
        ref: refs/heads/master
    - name: Provision Production
      run: ansible-playbook provision.yml --inventory-file env/production --extra-vars="ansible_user=${{ secrets.ansible_user}} ansible_password=${{ secrets.ansible_password}}"
      env:
        ANSIBLE_HOST_KEY_CHECKING: False
        ANSIBLE_SSH_COMMON_ARGS: '-o PreferredAuthentications=password'
